services:
  - type: web
    name: unique-school-systems
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "3000"
    autoDeploy: true
    buildFilter:
      ignoredPaths:
        - README.md
        - manual-slips/**
